version: "3.1"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: koal
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    koal:
        build: .
        env_file:
            - .env
        ports:
            - 3000:3000
